apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-d49d"
    labels:
        app: "myakscluster-d49d"
spec:
    type: LoadBalancer
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-d49d"